local Assert = require("tests.assert")
local Scene = require("editor.scene_view")
local Level = require("editor.level")
local Gizmo = require("editor.transform_gizmo")
local tests = {}
local function add(name, fn) tests[#tests + 1] = {name = name, fn = fn} end
local function scene(x, y)
    local level = Level.new()
    local object = level:addLObject(x or 0, y or 0)
    local view = Scene.new(32, level)
    view:setViewport(100, 80, 600, 400)
    view.selectedLObject = object
    return view, object
end
local function grab(view, axis)
    local handles = Gizmo.handles(view)
    if axis == "free" then view:mousepressed(handles.free.x + 8, handles.free.y + 8, 1)
    elseif axis == "x" then view:mousepressed(handles.x + 45, handles.y, 1)
    else view:mousepressed(handles.x, handles.y - 45, 1) end
end
local function grabRotation(view)
    local handles, offset = Gizmo.handles(view), 60 / math.sqrt(2)
    view:mousepressed(handles.x + offset, handles.y - offset, 1)
    Assert.equal("z", view.drag and view.drag.axis)
end
local function rotatePointer(view, degrees)
    local handles, angle = Gizmo.handles(view), math.rad(degrees)
    local x, y = handles.x + math.cos(angle) * 60, handles.y + math.sin(angle) * 60
    view:mousemoved(x, y, x - view.drag.pointerX, y - view.drag.pointerY)
end

add("Gizmo axes constrain movement and its square permits free movement", function()
    for _, axis in ipairs({"x", "y", "free"}) do
        local view, object = scene(20, 30)
        grab(view, axis)
        Assert.equal(axis, view.drag.axis)
        view:mousemoved(0, 0, 12, -18)
        Assert.equal(axis == "y" and 20 or 32, object.transform.x)
        Assert.equal(axis == "x" and 30 or 12, object.transform.y)
        view:mousereleased(0, 0, 1)
        Assert.equal(nil, view.drag)
    end
end)

add("Object clicks select without dragging and gizmo handles keep their screen size", function()
    local view, object = scene()
    view.selectedLObject = nil
    local x, y = view:worldToScreen(0, 0)
    view:mousepressed(x, y, 1)
    view:mousemoved(x + 50, y + 50, 50, 50)
    Assert.equal(object, view.selectedLObject)
    Assert.equal(false, view.isDraggingLObject)
    Assert.equal(0, object.transform.x)
    for _, zoom in ipairs({0.25, 1, 4}) do
        view.zoom, view.cameraX, view.cameraY = zoom, 15, -20
        local handles = Gizmo.handles(view)
        Assert.equal(16, handles.free.w)
        Assert.equal("x", Gizmo.hit(view, handles.x + 65, handles.y))
        grab(view, "free")
        view:mousemoved(0, 0, 8, -8)
        Assert.equal(8 / zoom, object.transform.x)
        Assert.equal(-8 / zoom, object.transform.y)
        view:keypressed("escape")
        Assert.equal(0, object.transform.x)
        Assert.equal(0, object.transform.y)
    end
end)

add("Snap steps are relative to the drag start and preserve the locked axis", function()
    local view, object = scene(3, 7)
    view.zoom = 2
    assert(view:setSnap("translate", true, 10))
    grab(view, "x")
    for _ = 1, 12 do view:mousemoved(0, 0, 1, -2) end
    Assert.equal(13, object.transform.x)
    Assert.equal(7, object.transform.y)
    view:mousereleased(0, 0, 1)
    object.transform.x, object.transform.y = -3, -7
    grab(view, "free")
    view:mousemoved(-100, -100, -12, -12)
    Assert.equal(-13, object.transform.x)
    Assert.equal(-17, object.transform.y)
    view:keypressed("escape")
    Assert.equal(-3, object.transform.x)
    Assert.equal(-7, object.transform.y)
    assert(view:setSnap("translate", false, 0.5))
    Assert.equal(1.3, view:snapValue(1.3))
    assert(view:setSnap("translate", true, 0.5))
    Assert.equal(1.5, view:snapValue(1.3))
    Assert.equal(-1.5, view:snapValue(-1.3))
end)

add("Snap panel consumes pointer and text input and rejects invalid units", function()
    local app = require("editor.app").new()
    local controls, view = app.viewportControls, app.sceneView
    local object = app.level:addLObject(0, 0)
    view.selectedLObject = object
    local vx, vy, vw = view:getViewport()
    Assert.truthy(controls.x > vx + vw / 2)
    local check, field = controls:rects()
    app:mousepressed(check.x + 5, check.y + 5, 1)
    Assert.equal(true, view.snapSettings.translate.enabled)
    Assert.equal(object, view.selectedLObject)
    Assert.equal(false, view.isPanning)
    local zoom = view.zoom
    app.uiRoot:wheelmoved(check.x + 5, check.y + 5, 2)
    Assert.equal(zoom, view.zoom)
    app:mousepressed(field.x + 5, field.y + 5, 1)
    app:textinput("12.5")
    app:keypressed("return")
    Assert.equal(12.5, view.snapSettings.translate.unit)
    for _, invalid in ipairs({"0", "-10", "nan", "1e999"}) do
        app:mousepressed(field.x + 5, field.y + 5, 1)
        app:textinput(invalid)
        app:keypressed("return")
        Assert.equal(12.5, view.snapSettings.translate.unit)
    end
    app:mousepressed(field.x + 5, field.y + 5, 1)
    app:textinput("50")
    app:keypressed("escape")
    Assert.equal(12.5, view.snapSettings.translate.unit)
    app:mousepressed(field.x + 5, field.y + 5, 1)
    app:textinput("8")
    local sx, sy = view:worldToScreen(0, 0)
    app:mousepressed(sx, sy + 40, 1)
    Assert.equal(8, view.snapSettings.translate.unit)
    app.sceneView.selectedLObject = object
    app:draw()
    if os.getenv("LOVE_LABO_GIZMO_PREVIEW") then
        local data = love.image.newImageData(64, 32)
        data:mapPixel(function(x, y)
            if math.abs(x - 32) < 2 or math.abs(y - 16) < 2 then return 1, 0.75, 0.2, 1 end
            return 0.15, 0.55, 0.9, 1
        end)
        local image = love.graphics.newImage(data)
        data:release()
        view.spriteAssets = {
            preview = function(_, authoring)
                local preview = assert(require("core.lobject").new(1, authoring))
                preview:addComponent("first", require("engine").SpriteComponent, {image = "preview"})
                preview:addComponent("second", require("engine").SpriteComponent, {x = 80, y = 30, image = "preview"})
                return preview
            end,
            image = function() return image end,
            draw = function(_, preview, sceneView, zoom)
                return require("core.sprite_renderer").draw(preview, function() return image end,
                    function(x, y) return sceneView:worldToScreen(x, y) end, zoom)
            end,
        }
        for _, mode in ipairs({"translate", "rotate", "scale"}) do
            view:setGizmoMode(mode)
            object.transform.rotation, object.transform.scaleX, object.transform.scaleY = 30, 1.5, 0.8
            object.transform.rotationX, object.transform.rotationY = 30, 45
            local canvas = love.graphics.newCanvas(love.graphics.getDimensions())
            love.graphics.push("all")
            love.graphics.setCanvas(canvas)
            app:draw()
            love.graphics.setCanvas()
            local data = canvas:newImageData()
            data:encode("png", "gizmo-" .. mode .. "-preview.png")
            data:release(); canvas:release(); love.graphics.pop()
        end
        view.spriteAssets = nil
        image:release()
    end
    assert(app:startPlay())
    app:draw()
    Assert.equal(false, controls.visible)
    assert(app:stopPlay())
    app:draw()
    Assert.equal(true, controls.visible)
end)

add("Gizmo capture survives viewport exit and Escape restores the starting position", function()
    local app = require("editor.app").new()
    local object = app.level:addLObject(0, 0)
    app.sceneView.selectedLObject = object
    local handles = Gizmo.handles(app.sceneView)
    app:mousepressed(handles.free.x + 8, handles.free.y + 8, 1)
    Assert.equal(app.sceneWidget, app.uiRoot.captured)
    app:mousemoved(-50, -50, -100, -100)
    Assert.equal(-100, object.transform.x)
    app:keypressed("escape")
    Assert.equal(0, object.transform.x)
    Assert.equal(0, object.transform.y)
    Assert.equal(nil, app.uiRoot.captured)
    Assert.equal(nil, app.sceneView.drag)
end)
add("Snapped duplication uses world coordinates without sharing transforms", function()
    local view, object = scene(3, 7)
    view.zoom = 2
    assert(view:setSnap("translate", true, 10))
    local x, y = view:worldToScreen(24, -16)
    view:keypressed("d", true, x, y)
    Assert.equal(23, view.selectedLObject.transform.x)
    Assert.equal(-13, view.selectedLObject.transform.y)
    Assert.equal(3, object.transform.x)
    Assert.equal(7, object.transform.y)
end)

add("Translation center is a circle and snap 100 preserves an offset of 20", function()
    local view, object = scene(20, 15)
    local handles = Gizmo.handles(view)
    Assert.equal("free", Gizmo.hit(view, handles.x, handles.y))
    Assert.equal(nil, Gizmo.hit(view, handles.x + 8, handles.y - 8))
    assert(view:setSnap("translate", true, 100))
    for _, direction in ipairs({1, -1}) do
        grab(view, "x")
        for _ = 1, 70 do view:mousemoved(0, 0, direction, 1) end
        Assert.equal(direction == 1 and 120 or -80, object.transform.x)
        Assert.equal(15, object.transform.y)
        view:keypressed("escape")
        Assert.equal(20, object.transform.x)
    end
end)

local function near(expected, actual)
    Assert.truthy(math.abs(expected - actual) < 0.000001, "expected " .. expected .. ", got " .. actual)
end

add("Z rotation follows the ring and crosses the angle boundary continuously", function()
    local view, object = scene(20, 30)
    object.transform.rotation = 30
    view:setGizmoMode("rotate")
    local handles = Gizmo.handles(view)
    Assert.equal(nil, Gizmo.hit(view, handles.x, handles.y))
    grabRotation(view)
    rotatePointer(view, 45)
    near(120, object.transform.rotation)
    Assert.equal(20, object.transform.x)
    Assert.equal(30, object.transform.y)
    view:keypressed("escape")
    near(30, object.transform.rotation)
    grabRotation(view)
    for _, angle in ipairs({45, 135, 179, -179}) do rotatePointer(view, angle) end
    near(256, object.transform.rotation)
    view:mousereleased(0, 0, 1)
end)

add("Scale center changes both axes proportionally and local axis handles isolate dimensions", function()
    local view, object = scene()
    object.transform.scaleX, object.transform.scaleY = 2, 3
    view:setGizmoMode("scale")
    grab(view, "free")
    view:mousemoved(0, 0, 100, 0)
    near(2 * math.exp(1), object.transform.scaleX)
    near(3 * math.exp(1), object.transform.scaleY)
    view:mousemoved(0, 0, 0, -100)
    near(2 * math.exp(2), object.transform.scaleX)
    view:mousemoved(0, 0, -300, 300)
    Assert.truthy(object.transform.scaleX < 2 and object.transform.scaleY < 3)
    near(1.5, object.transform.scaleY / object.transform.scaleX)
    view:keypressed("escape")
    near(2, object.transform.scaleX); near(3, object.transform.scaleY)
    object.transform.rotation = 90
    local handles = Gizmo.handles(view)
    view:mousepressed(handles.x + handles.ux * 70, handles.y + handles.uy * 70, 1)
    Assert.equal("x", view.drag.axis)
    view:mousemoved(0, 0, 0, 100)
    near(2 * math.exp(1), object.transform.scaleX)
    near(3, object.transform.scaleY)
    view:keypressed("escape")
    handles = Gizmo.handles(view)
    view:mousepressed(handles.x + handles.vx * 70, handles.y + handles.vy * 70, 1)
    view:mousemoved(0, 0, 100, 0)
    near(2, object.transform.scaleX)
    near(3 * math.exp(1), object.transform.scaleY)
    view:keypressed("escape")
    grab(view, "free")
    view:mousemoved(0, 0, -10000, 10000)
    near(0.01, object.transform.scaleX)
    near(0.015, object.transform.scaleY)
    view:keypressed("escape")
end)

add("UE mode shortcuts respect numeric input focus without mode buttons", function()
    local app = require("editor.app").new()
    app.level:addLObject(0, 0)
    app.sceneView.selectedLObject = app.level.lobjects[1]
    app:keypressed("e"); Assert.equal("rotate", app.sceneView.gizmoMode)
    app:keypressed("r"); Assert.equal("scale", app.sceneView.gizmoMode)
    app:keypressed("w"); Assert.equal("translate", app.sceneView.gizmoMode)
    app:keypressed("space"); Assert.equal("rotate", app.sceneView.gizmoMode)
    local controls = app.viewportControls
    Assert.equal(nil, controls.modeRects)
    app:keypressed("r")
    Assert.equal("scale", app.sceneView.gizmoMode)
    local _, field = controls:rects()
    app:mousepressed(field.x + 5, field.y + 5, 1)
    app:keypressed("e")
    Assert.equal("scale", app.sceneView.gizmoMode)
    app:textinput("1e2"); app:keypressed("return")
    Assert.equal(100, app.sceneView.snapSettings.translate.unit)
    local left = love.graphics.getWidth() - app.inspector.width
    app:mousepressed(left + 110, 239, 1)
    app:keypressed("w")
    Assert.equal("scale", app.sceneView.gizmoMode)
    app:textinput("45"); app:keypressed("return")
    Assert.equal(45, app.level.lobjects[1].transform.rotation)
    app:mousepressed(left + 110, 269, 1)
    app:textinput("2"); app:keypressed("return")
    Assert.equal(2, app.level.lobjects[1].transform.scaleX)
    app:mousepressed(left + 110, 301, 1)
    app:textinput("0"); app:keypressed("return")
    Assert.equal(1, app.level.lobjects[1].transform.scaleY)
    local handles = Gizmo.handles(app.sceneView)
    app:mousepressed(handles.x, handles.y, 1)
    app:mousemoved(handles.x + 50, handles.y, 50, 0)
    Assert.truthy(app.level.lobjects[1].transform.scaleX > 2)
    app:keypressed("e")
    Assert.equal("rotate", app.sceneView.gizmoMode)
    Assert.equal(2, app.level.lobjects[1].transform.scaleX)
    Assert.equal(nil, app.uiRoot.captured)
    app:draw()
end)

add("Rotation and scale persist duplicate and enter an independent Runtime world", function()
    local level = Level.new()
    local object = level:addLObject(20, 30)
    object.transform.rotation, object.transform.scaleX, object.transform.scaleY = 75, 2, 0.5
    local data = level:toData()
    local loaded = assert(Level.fromData(data))
    local duplicate = loaded:duplicateLObject(loaded.lobjects[1])
    Assert.equal(75, duplicate.transform.rotation)
    Assert.equal(2, duplicate.transform.scaleX)
    Assert.equal(0.5, duplicate.transform.scaleY)
    local world = assert(require("core.world").fromLevelData(loaded:toData()))
    world.lobjects[1].transform.rotation = 100
    Assert.equal(75, loaded.lobjects[1].transform.rotation)
    local legacy = assert(Level.fromData({formatVersion = 2, lobjects = {{authoringId = 1, transform = {x = 0, y = 0}}}}))
    Assert.equal(0, legacy.lobjects[1].transform.rotation)
    Assert.equal(1, legacy.lobjects[1].transform.scaleX)
    Assert.equal(nil, legacy:toData().lobjects[1].transform.rotation)
    for _, invalid in ipairs({0, -1, false, math.huge}) do
        data.lobjects[1].transform.scaleX = invalid
        Assert.equal(nil, Level.fromData(data))
        Assert.equal(nil, require("core.world").fromLevelData(data))
    end
end)

add("Rotated scaled Sprites render and select using the same transform", function()
    local E = require("engine")
    local object = assert(require("core.lobject").new(1, {transform = {x = 50, y = 60, rotation = 90, scaleX = 2, scaleY = 3}}))
    local sprite = object:addComponent("sprite", E.SpriteComponent, {x = 10, image = "example"})
    local x, y = sprite:getWorldPosition()
    near(50, x); near(80, y)
    local data = love.image.newImageData(20, 10)
    data:mapPixel(function() return 1, 0, 0, 1 end)
    local image = love.graphics.newImage(data)
    data:release()
    local Renderer = require("core.sprite_renderer")
    Assert.equal(true, Renderer.hit(object, function() return image end, 50, 95))
    Assert.equal(false, Renderer.hit(object, function() return image end, 70, 80))
    local canvas = love.graphics.newCanvas(140, 140)
    love.graphics.push("all")
    love.graphics.setCanvas(canvas)
    love.graphics.clear(0, 0, 0, 0)
    assert(Renderer.draw(object, function() return image end, function(wx, wy) return wx, wy end, 1))
    love.graphics.setCanvas()
    local pixels = canvas:newImageData()
    local _, _, _, inside = pixels:getPixel(50, 95)
    local _, _, _, outside = pixels:getPixel(70, 80)
    Assert.equal(1, inside); Assert.equal(0, outside)
    pixels:release(); canvas:release(); image:release(); love.graphics.pop()
end)

add("Grid axes and transform axes use identical theme colors", function()
    local view = scene(100, 100)
    local colors = {x = require("editor.theme").color("axisX"), y = require("editor.theme").color("axisY")}
    local canvas = love.graphics.newCanvas(800, 600)
    love.graphics.push("all")
    love.graphics.setCanvas(canvas)
    love.graphics.clear(0, 0, 0, 0)
    view:drawWorldAxes()
    Gizmo.draw(view)
    love.graphics.setCanvas()
    local pixels = canvas:newImageData()
    local function sameColor(x, y, expected)
        local r, g, b = pixels:getPixel(x, y)
        Assert.truthy(math.abs(r - expected[1]) < 0.005 and math.abs(g - expected[2]) < 0.005 and math.abs(b - expected[3]) < 0.005)
    end
    local x, y = view:worldToScreen(0, 0)
    sameColor(x + 80, y, colors.x); sameColor(x, y + 80, colors.y)
    local handles = Gizmo.handles(view)
    sameColor(handles.x + 30, handles.y, colors.x); sameColor(handles.x, handles.y - 30, colors.y)
    pixels:release(); canvas:release(); love.graphics.pop()
end)

add("Rotation wraps into 0 to 360 for dragging Inspector loading and saving", function()
    local view, object = scene()
    object.transform.rotation = 350
    view:setGizmoMode("rotate")
    grabRotation(view)
    rotatePointer(view, -15)
    near(20, object.transform.rotation)
    view:mousereleased(0, 0, 1)
    local Inspector = require("editor.inspector")
    local inspector = Inspector.new(view.level)
    assert(inspector:beginEdit("rotation", object))
    inspector:textinput("-740"); inspector:keypressed("return")
    near(340, object.transform.rotation)
    object.transform.rotation = 1080
    local data = view.level:toData()
    Assert.equal(nil, data.lobjects[1].transform.rotation)
    data.lobjects[1].transform.rotation = -10
    local loaded = assert(Level.fromData(data))
    Assert.equal(350, loaded.lobjects[1].transform.rotation)
    Assert.equal(350, assert(require("core.world").fromLevelData(data)).lobjects[1].transform.rotation)
end)

add("Independent snap buttons values and toggles survive preference reload", function()
    local Settings = require("editor.snap_settings")
    local stored = {}
    local app = require("editor.app").new(nil, nil, {snapSettings = Settings.copy(),
        saveSnapSettings = function(values)
            return Settings.save(values, function(path, bytes) stored[path] = bytes; return true end)
        end})
    local controls = app.viewportControls
    for _, pair in ipairs({{"translate", "100"}, {"rotate", "30"}, {"scale", "0.25"}}) do
        local button, field = controls:rects(pair[1])
        app:mousepressed(field.x + 5, field.y + 5, 1)
        app:textinput(pair[2])
        -- 토글 클릭 시 편집 중인 새 값을 먼저 확정해야 한다.
        app:mousepressed(button.x + 5, button.y + 5, 1)
        Assert.equal(tonumber(pair[2]), app.sceneView.snapSettings[pair[1]].unit)
        Assert.equal(true, app.sceneView.snapSettings[pair[1]].enabled)
        Assert.equal("translate", app.sceneView.gizmoMode)
    end
    local reload = Settings.load(function(path) return stored[path] end)
    local nextApp = require("editor.app").new(nil, nil, {snapSettings = reload})
    Assert.equal(100, nextApp.sceneView.snapSettings.translate.unit)
    Assert.equal(30, nextApp.sceneView.snapSettings.rotate.unit)
    Assert.equal(0.25, nextApp.sceneView.snapSettings.scale.unit)
    for _, mode in ipairs({"translate", "rotate", "scale"}) do
        Assert.equal(true, nextApp.sceneView.snapSettings[mode].enabled)
        app.sceneView:setGizmoMode(mode)
    end
    local button = controls:rects("rotate")
    app:mousepressed(button.x + 5, button.y + 5, 1)
    Assert.equal(false, app.sceneView.snapSettings.rotate.enabled)
    Assert.equal(true, app.sceneView.snapSettings.translate.enabled)
    Assert.equal(true, app.sceneView.snapSettings.scale.enabled)
    reload = Settings.load(function(path) return stored[path] end)
    Assert.equal(false, reload.rotate.enabled)
    Assert.equal(30, reload.rotate.unit)
    Assert.equal(15, Settings.load(function() return "invalid JSON" end).rotate.unit)
end)

add("Rotation and scale snap from their initial values while retaining uniform proportions", function()
    local view, object = scene(20, 30)
    assert(view:setSnap("translate", true, 100))
    assert(view:setSnap("rotate", true, 30))
    assert(view:setSnap("scale", true, 0.25))
    object.transform.rotation = 350
    view:setGizmoMode("rotate")
    grabRotation(view)
    rotatePointer(view, -25)
    near(20, object.transform.rotation)
    view:mousereleased(0, 0, 1)
    object.transform.rotation, object.transform.scaleX, object.transform.scaleY = 0, 2, 3
    view:setGizmoMode("scale")
    grab(view, "free")
    view:mousemoved(0, 0, math.log(1.1) * 100, 0)
    near(2.25, object.transform.scaleX)
    near(3.375, object.transform.scaleY)
    near(1.5, object.transform.scaleY / object.transform.scaleX)
    Assert.equal(20, object.transform.x)
    Assert.equal(30, object.transform.y)
    view:keypressed("escape")
    grab(view, "y")
    view:mousemoved(0, 0, 0, -math.log(1.1) * 100)
    near(2, object.transform.scaleX)
    near(3.25, object.transform.scaleY)
    view:keypressed("escape")
end)

add("Selected rendering bounds include every transformed Sprite and hide missing images", function()
    local object = assert(require("core.lobject").new(1, {transform = {x = 60, y = 60, rotation = 90, scaleX = 2, scaleY = 3}}))
    local Sprite = require("engine").SpriteComponent
    object:addComponent("first", Sprite, {image = "image"})
    object:addComponent("second", Sprite, {x = 20, image = "image"})
    object:addComponent("missing", Sprite, {image = "missing"})
    local data = love.image.newImageData(20, 10)
    local image = love.graphics.newImage(data)
    data:release()
    local canvas = love.graphics.newCanvas(160, 160)
    love.graphics.push("all")
    love.graphics.setCanvas(canvas)
    love.graphics.clear(0, 0, 0, 0)
    love.graphics.setColor(0, 1, 0, 1)
    love.graphics.setLineWidth(2)
    require("core.sprite_renderer").outline(object, function(ref) return ref == "image" and image or nil end,
        function(x, y) return x, y end)
    love.graphics.setCanvas()
    local pixels = canvas:newImageData()
    local _, g1, _, a1 = pixels:getPixel(60, 40)
    local _, g2, _, a2 = pixels:getPixel(60, 120)
    local _, _, _, center = pixels:getPixel(60, 60)
    Assert.equal(1, g1); Assert.equal(1, a1)
    Assert.equal(1, g2); Assert.equal(1, a2)
    Assert.equal(0, center)
    pixels:release(); canvas:release(); image:release(); love.graphics.pop()
end)
add("Default grid uses 100 world units and snap fields fit three digits", function()
    Assert.equal(100, Scene.new().gridSize)
    local controls = require("editor.ui.viewport_controls").new(Scene.new())
    controls:setBounds(0, 0, controls:preferredWidth(), 56)
    local rects = controls:snapRects()
    for _, mode in ipairs({"translate", "rotate", "scale"}) do
        Assert.equal(love.graphics.getFont():getWidth("000") + 20, rects[mode].field.w)
        Assert.equal(rects.translate.field.y, rects[mode].field.y)
        Assert.truthy(rects[mode].field.x + rects[mode].field.w <= controls.width)
    end
    Assert.equal(56, controls:preferredHeight(controls.width))
    controls:setBounds(0, 0, 180, 120)
    Assert.truthy(controls:snapRects().scale.field.y > controls:snapRects().translate.field.y)
end)

add("XY rotations project Sprite geometry and share render picking and outline matrices", function()
    local T, Renderer = require("core.transform"), require("core.sprite_renderer")
    local object = assert(require("core.lobject").new(1, {transform = {x = 80, y = 80, rotationX = 60, rotationY = 60}}))
    object:addComponent("sprite", require("engine").SpriteComponent, {image = "example"})
    local x, y = T.point(object.transform, 8, 4)
    near(87, x); near(82, y)
    local lx, ly = T.inversePoint(object.transform, x, y)
    near(8, lx); near(4, ly)
    local data = love.image.newImageData(40, 40)
    data:mapPixel(function() return 1, 0, 0, 1 end)
    local image = love.graphics.newImage(data); data:release()
    local resolve = function() return image end
    Assert.truthy(Renderer.hit(object, resolve, 87, 82))
    Assert.equal(false, Renderer.hit(object, resolve, 110, 82))
    local canvas = love.graphics.newCanvas(160, 160)
    love.graphics.push("all"); love.graphics.setCanvas(canvas); love.graphics.clear(0, 0, 0, 0)
    Renderer.draw(object, resolve, function(wx, wy) return wx, wy end, 1)
    love.graphics.setCanvas()
    local pixels = canvas:newImageData()
    local _, _, _, inside = pixels:getPixel(87, 82)
    local _, _, _, outside = pixels:getPixel(110, 82)
    Assert.equal(1, inside); Assert.equal(0, outside); pixels:release()
    love.graphics.setCanvas(canvas); love.graphics.clear(0, 0, 0, 0); love.graphics.setColor(0, 1, 0, 1); love.graphics.setLineWidth(2)
    Renderer.outline(object, resolve, function(wx, wy) return wx, wy end)
    love.graphics.setCanvas()
    pixels = canvas:newImageData()
    local _, green, _, edge = pixels:getPixel(95, 90)
    Assert.equal(1, green); Assert.equal(1, edge); pixels:release()
    love.graphics.setCanvas(); love.graphics.pop(); canvas:release(); image:release()
    object.transform.rotationX = 90
    Assert.equal(nil, T.inversePoint(object.transform, 80, 80))
    Assert.equal(false, Renderer.hit(object, resolve, 80, 80))
end)

add("XY rotations normalize serialize duplicate and stay independent in Runtime", function()
    local level = Level.new()
    local object = level:addLObject(0, 0)
    local inspector = require("editor.inspector").new(level)
    assert(inspector:beginEdit("rotationX", object)); inspector.editText = "-30"; assert(inspector:commitEdit())
    assert(inspector:beginEdit("rotationY", object)); inspector.editText = "420"; assert(inspector:commitEdit())
    Assert.equal(330, object.transform.rotationX); Assert.equal(60, object.transform.rotationY)
    local loaded = assert(Level.fromData(level:toData()))
    local duplicate = loaded:duplicateLObject(loaded.lobjects[1])
    Assert.equal(330, duplicate.transform.rotationX); Assert.equal(60, duplicate.transform.rotationY)
    local world = assert(require("core.world").fromLevelData(loaded:toData()))
    world.lobjects[1].transform.rotationX = 10
    Assert.equal(330, loaded.lobjects[1].transform.rotationX)
    for _, invalid in ipairs({false, math.huge, "30"}) do
        local data = level:toData(); data.lobjects[1].transform.rotationY = invalid
        Assert.equal(nil, Level.fromData(data))
        object.transform.rotationY = invalid
        Assert.equal(nil, Level.fromData(level:toData()))
        object.transform.rotationY = 60
    end
    local view = scene(); view.selectedLObject.transform.rotationX = 30; view.selectedLObject.transform.rotationY = 45
    view:setGizmoMode("rotate")
    grabRotation(view); rotatePointer(view, 45)
    near(90, view.selectedLObject.transform.rotation)
    Assert.equal(30, view.selectedLObject.transform.rotationX); Assert.equal(45, view.selectedLObject.transform.rotationY)
end)
add("Rotation quarter handles map vertical to X horizontal to Y and arc to Z", function()
    local view, object = scene(20, 30)
    view:setGizmoMode("rotate")
    local h = Gizmo.handles(view)
    Assert.equal("x", Gizmo.hit(view, h.x, h.y - 40))
    Assert.equal("y", Gizmo.hit(view, h.x + 40, h.y))
    Assert.equal("z", Gizmo.hit(view, h.x + 60 / math.sqrt(2), h.y - 60 / math.sqrt(2)))
    Assert.equal(nil, Gizmo.hit(view, h.x - 60, h.y))
    Assert.equal(nil, Gizmo.hit(view, h.x, h.y + 60))
    Assert.equal(nil, Gizmo.hit(view, h.x, h.y))
    for _, axis in ipairs({"x", "y"}) do
        local field = axis == "x" and "rotationX" or "rotationY"
        object.transform[field] = 350
        assert(view:setSnap("rotate", true, 30))
        view:mousepressed(axis == "x" and h.x or h.x + 40, axis == "x" and h.y - 40 or h.y, 1)
        Assert.equal(axis, view.drag.axis)
        view:mousemoved(0, 0, 20, -20)
        near(20, object.transform[field])
        Assert.equal(0, object.transform.rotation)
        Assert.equal(20, object.transform.x); Assert.equal(30, object.transform.y)
        if axis == "x" then
            Assert.equal("x", Gizmo.hit(view, h.x, h.y + 40))
            Assert.equal(nil, Gizmo.hit(view, h.x + 40, h.y))
        else
            Assert.equal("y", Gizmo.hit(view, h.x - 40, h.y))
            Assert.equal(nil, Gizmo.hit(view, h.x, h.y - 40))
        end
        view:keypressed("escape"); near(350, object.transform[field])
        object.transform[field] = 0
    end
    grabRotation(view)
    Assert.equal("z", Gizmo.hit(view, h.x - 60, h.y))
    Assert.equal(nil, Gizmo.hit(view, h.x, h.y - 40))
end)

add("Rotation dragging displays only the selected diameter or full Z ring", function()
    local view = scene()
    view:setGizmoMode("rotate")
    local h = Gizmo.handles(view)
    local canvas = love.graphics.newCanvas(800, 600)
    local function pixelsFor(axis)
        view.drag = axis and Gizmo.begin(view, axis, h.x + 40, h.y - 40) or nil
        love.graphics.push("all"); love.graphics.setCanvas(canvas); love.graphics.clear(0, 0, 0, 0)
        Gizmo.draw(view); love.graphics.setCanvas(); love.graphics.pop()
        local pixels = canvas:newImageData()
        if os.getenv("LOVE_LABO_GIZMO_PREVIEW") then pixels:encode("png", "rotation-" .. (axis or "idle") .. "-preview.png") end
        return pixels
    end
    local function alpha(pixels, dx, dy)
        local _, _, _, a = pixels:getPixel(h.x + dx, h.y + dy); return a
    end
    local idle = pixelsFor()
    Assert.truthy(alpha(idle, 0, -30) > 0); Assert.truthy(alpha(idle, 30, 0) > 0)
    Assert.truthy(alpha(idle, 42, -42) > 0)
    Assert.equal(0, alpha(idle, -30, 0)); Assert.equal(0, alpha(idle, 0, 30)); idle:release()
    local x = pixelsFor("x")
    Assert.truthy(alpha(x, 0, 30) > 0); Assert.truthy(alpha(x, 0, -30) > 0)
    Assert.equal(0, alpha(x, 30, 0)); Assert.equal(0, alpha(x, 42, -42)); x:release()
    local y = pixelsFor("y")
    Assert.truthy(alpha(y, -30, 0) > 0); Assert.truthy(alpha(y, 30, 0) > 0)
    Assert.equal(0, alpha(y, 0, -30)); Assert.equal(0, alpha(y, 42, -42)); y:release()
    local z = pixelsFor("z")
    Assert.truthy(alpha(z, -60, 0) > 0); Assert.truthy(alpha(z, 0, 60) > 0)
    Assert.equal(0, alpha(z, 0, -30)); z:release(); canvas:release()
end)
return tests
